`timescale 1ns / 1ps

// Block Design: Core.bd
// generated by autowire.py

module Uranus(
    input [31:0] ram_read_data,
    output [31:0] ram_write_data,
    output [3:0] ram_write_en,
    output ram_en,
    input clk,
    input rst,
    output [3:0] debug_reg_write_en,
    output rom_en,
    output [3:0] rom_write_en,
    output [31:0] rom_write_data,
    input [31:0] rom_read_data,
    output [31:0] debug_reg_write_data,
    output [4:0] debug_reg_write_addr,
    output [31:0] debug_pc_addr,
    output [31:0] rom_addr,
    output [31:0] ram_addr,
    input [4:0] interrupt,
    output debug_exception_flag,
    input halt
);

    wire[31:0] ifid_0_addr_out;
    wire id_0_write_reg_en;
    wire[4:0] id_0_write_reg_addr;
    wire[31:0] id_0_operand_2;
    wire[31:0] id_0_operand_1;
    wire[4:0] id_0_shamt;
    wire[5:0] id_0_funct;
    wire[4:0] id_0_reg_addr_2;
    wire[4:0] id_0_reg_addr_1;
    wire id_0_reg_read_en_2;
    wire id_0_reg_read_en_1;
    wire[5:0] idex_0_funct_out;
    wire[4:0] idex_0_shamt_out;
    wire[31:0] idex_0_operand_1_out;
    wire[31:0] idex_0_operand_2_out;
    wire idex_0_write_reg_en_out;
    wire[4:0] idex_0_write_reg_addr_out;
    wire[31:0] ex_0_result_out;
    wire ex_0_write_reg_en_out;
    wire[4:0] ex_0_write_reg_addr_out;
    wire[31:0] exmem_0_result_out;
    wire exmem_0_write_reg_en_out;
    wire[4:0] exmem_0_write_reg_addr_out;
    wire[31:0] mem_0_result_out;
    wire mem_0_write_reg_en_out;
    wire[4:0] mem_0_write_reg_addr_out;
    wire[31:0] regreadproxy_0_read_data_1;
    wire[31:0] regreadproxy_0_read_data_2;
    wire[31:0] regfile_0_read_data_1;
    wire[31:0] regfile_0_read_data_2;
    wire[31:0] hilo_0_hi;
    wire[31:0] hilo_0_lo;
    wire ex_0_hilo_write_en;
    wire[31:0] ex_0_hi_out;
    wire[31:0] ex_0_lo_out;
    wire exmem_0_hilo_write_en_out;
    wire[31:0] exmem_0_hi_out;
    wire[31:0] exmem_0_lo_out;
    wire mem_0_hilo_write_en_out;
    wire[31:0] mem_0_hi_out;
    wire[31:0] mem_0_lo_out;
    wire[31:0] hiloreadproxy_0_hi_out;
    wire[31:0] hiloreadproxy_0_lo_out;
    wire id_0_mem_read_flag;
    wire id_0_mem_write_flag;
    wire id_0_mem_sign_ext_flag;
    wire[3:0] id_0_mem_sel;
    wire[31:0] id_0_mem_write_data;
    wire idex_0_mem_read_flag_out;
    wire idex_0_mem_write_flag_out;
    wire idex_0_mem_sign_ext_flag_out;
    wire[3:0] idex_0_mem_sel_out;
    wire[31:0] idex_0_mem_write_data_out;
    wire ex_0_mem_read_flag_out;
    wire ex_0_mem_write_flag_out;
    wire ex_0_mem_sign_ext_flag_out;
    wire[3:0] ex_0_mem_sel_out;
    wire[31:0] ex_0_mem_write_data_out;
    wire exmem_0_mem_read_flag_out;
    wire exmem_0_mem_write_flag_out;
    wire exmem_0_mem_sign_ext_flag_out;
    wire[3:0] exmem_0_mem_sel_out;
    wire[31:0] exmem_0_mem_write_data_out;
    wire[31:0] ram_read_data_1 = ram_read_data;
    wire[31:0] mem_0_ram_write_data;
    wire[3:0] mem_0_ram_write_sel;
    wire mem_0_ram_en;
    wire clk_1 = clk;
    wire rst_1 = rst;
    wire[3:0] memwb_0_debug_reg_write_en;
    wire pc_0_rom_en;
    wire[3:0] pc_0_rom_write_en;
    wire[31:0] pc_0_rom_write_data;
    wire id_0_stall_request;
    wire ex_0_stall_request;
    wire regreadproxy_0_load_related_1;
    wire regreadproxy_0_load_related_2;
    wire ex_0_ex_load_flag;
    wire pipelinecontroller_0_stall_pc;
    wire pipelinecontroller_0_stall_if;
    wire pipelinecontroller_0_stall_id;
    wire pipelinecontroller_0_stall_ex;
    wire pipelinecontroller_0_stall_mem;
    wire pipelinecontroller_0_stall_wb;
    wire[31:0] rom_read_data_1 = rom_read_data;
    wire[31:0] ifid_0_inst_out;
    wire mem_0_mem_write_flag_out;
    wire mem_0_mem_sign_ext_flag_out;
    wire[3:0] mem_0_mem_sel_out;
    wire memwb_0_mem_read_flag_out;
    wire[31:0] memwb_0_ram_read_data_out;
    wire memwb_0_mem_write_flag_out;
    wire memwb_0_mem_sign_ext_flag_out;
    wire[3:0] memwb_0_mem_sel_out;
    wire[31:0] memwb_0_result_out;
    wire[31:0] wb_0_result_out;
    wire memwb_0_write_reg_en_out;
    wire wb_0_write_reg_en_out;
    wire[4:0] memwb_0_write_reg_addr_out;
    wire[4:0] wb_0_write_reg_addr_out;
    wire memwb_0_hilo_write_en_out;
    wire wb_0_hilo_write_en_out;
    wire[31:0] memwb_0_hi_out;
    wire[31:0] wb_0_hi_out;
    wire[31:0] memwb_0_lo_out;
    wire[31:0] wb_0_lo_out;
    wire[31:0] memwb_0_debug_pc_addr_out;
    wire[31:0] wb_0_debug_pc_addr_out;
    wire mem_0_mem_read_flag_out;
    wire mem_0_mem_load_flag;
    wire[31:0] pc_0_rom_addr;
    wire[31:0] pc_0_pc;
    wire id_0_cp0_write_flag;
    wire id_0_cp0_read_flag;
    wire[4:0] id_0_cp0_addr;
    wire[31:0] id_0_cp0_write_data;
    wire wb_0_cp0_write_en;
    wire[4:0] wb_0_cp0_addr_out;
    wire[31:0] wb_0_cp0_write_data_out;
    wire[4:0] interrupt_1 = interrupt;
    wire memwb_0_cp0_write_en_out;
    wire[4:0] memwb_0_cp0_addr_out;
    wire[31:0] memwb_0_cp0_write_data_out;
    wire mem_0_cp0_write_en_out;
    wire[4:0] mem_0_cp0_addr_out;
    wire[31:0] mem_0_cp0_write_data_out;
    wire exmem_0_cp0_write_en_out;
    wire[4:0] exmem_0_cp0_addr_out;
    wire[31:0] exmem_0_cp0_write_data_out;
    wire ex_0_cp0_write_en;
    wire[4:0] ex_0_cp0_addr_out;
    wire[31:0] ex_0_cp0_write_data_out;
    wire idex_0_cp0_write_flag_out;
    wire idex_0_cp0_read_flag_out;
    wire[4:0] idex_0_cp0_addr_out;
    wire[31:0] idex_0_cp0_write_data_out;
    wire[31:0] cp0_0_data_out;
    wire[31:0] cp0readproxy_0_cp0_read_data_out;
    wire multdiv_0_done;
    wire[63:0] multdiv_0_result;
    wire pipelinecontroller_0_flush;
    wire[31:0] pipelinecontroller_0_exc_pc;
    wire id_0_delayslot_flag_out;
    wire[7:0] id_0_exception_type;
    wire[31:0] id_0_current_pc_addr;
    wire idex_0_current_delayslot_flag;
    wire[7:0] idex_0_exception_type_out;
    wire idex_0_delayslot_flag_out;
    wire[31:0] idex_0_current_pc_addr_out;
    wire[7:0] ex_0_exception_type_out;
    wire ex_0_delayslot_flag_out;
    wire[31:0] ex_0_current_pc_addr_out;
    wire[7:0] exmem_0_exception_type_out;
    wire exmem_0_delayslot_flag_out;
    wire[31:0] exmem_0_current_pc_addr_out;
    wire[31:0] mem_0_current_pc_addr_out;
    wire[31:0] cp0_0_status;
    wire[31:0] cp0_0_cause;
    wire[31:0] cp0_0_epc;
    wire[31:0] cp0readproxy_0_cp0_epc_out;
    wire[31:0] cp0readproxy_0_cp0_cause_out;
    wire[31:0] cp0readproxy_0_cp0_status_out;
    wire[31:0] mem_0_cp0_badvaddr_write_data;
    wire mem_0_delayslot_flag_out;
    wire[7:0] mem_0_exception_type_out;
    wire[31:0] mem_0_cp0_epc_out;
    wire[31:0] id_0_branch_addr;
    wire id_0_branch_flag;
    wire id_0_next_delayslot_flag_out;
    wire stall_all_1 = halt;
    wire[31:0] mem_0_ram_addr;

    assign ram_write_data = mem_0_ram_write_data;
    assign ram_write_en = mem_0_ram_write_sel;
    assign ram_en = mem_0_ram_en;
    assign debug_reg_write_en = memwb_0_debug_reg_write_en;
    assign rom_en = pc_0_rom_en;
    assign rom_write_en = pc_0_rom_write_en;
    assign rom_write_data = pc_0_rom_write_data;
    assign debug_reg_write_data = wb_0_result_out;
    assign debug_reg_write_addr = wb_0_write_reg_addr_out;
    assign debug_pc_addr = wb_0_debug_pc_addr_out;
    assign rom_addr = pc_0_rom_addr;
    assign debug_exception_flag = pipelinecontroller_0_flush;
    assign ram_addr = mem_0_ram_addr;

    IFID ifid_0(
        .addr_out(ifid_0_addr_out),
        .clk(clk_1),
        .rst(rst_1),
        .stall_current_stage(pipelinecontroller_0_stall_if),
        .stall_next_stage(pipelinecontroller_0_stall_id),
        .inst_in(rom_read_data_1),
        .inst_out(ifid_0_inst_out),
        .addr_in(pc_0_pc),
        .flush(pipelinecontroller_0_flush)
    );

    RegFile regfile_0(
        .read_addr_2(id_0_reg_addr_2),
        .read_addr_1(id_0_reg_addr_1),
        .read_en_2(id_0_reg_read_en_2),
        .read_en_1(id_0_reg_read_en_1),
        .read_data_1(regfile_0_read_data_1),
        .read_data_2(regfile_0_read_data_2),
        .clk(clk_1),
        .rst(rst_1),
        .write_data(wb_0_result_out),
        .write_en(wb_0_write_reg_en_out),
        .write_addr(wb_0_write_reg_addr_out)
    );

    EX ex_0(
        .funct(idex_0_funct_out),
        .shamt(idex_0_shamt_out),
        .operand_1(idex_0_operand_1_out),
        .operand_2(idex_0_operand_2_out),
        .write_reg_en_in(idex_0_write_reg_en_out),
        .write_reg_addr_in(idex_0_write_reg_addr_out),
        .result_out(ex_0_result_out),
        .write_reg_en_out(ex_0_write_reg_en_out),
        .write_reg_addr_out(ex_0_write_reg_addr_out),
        .hilo_write_en(ex_0_hilo_write_en),
        .hi_out(ex_0_hi_out),
        .lo_out(ex_0_lo_out),
        .hi_in(hiloreadproxy_0_hi_out),
        .lo_in(hiloreadproxy_0_lo_out),
        .mem_read_flag_in(idex_0_mem_read_flag_out),
        .mem_write_flag_in(idex_0_mem_write_flag_out),
        .mem_sign_ext_flag_in(idex_0_mem_sign_ext_flag_out),
        .mem_sel_in(idex_0_mem_sel_out),
        .mem_write_data_in(idex_0_mem_write_data_out),
        .mem_read_flag_out(ex_0_mem_read_flag_out),
        .mem_write_flag_out(ex_0_mem_write_flag_out),
        .mem_sign_ext_flag_out(ex_0_mem_sign_ext_flag_out),
        .mem_sel_out(ex_0_mem_sel_out),
        .mem_write_data_out(ex_0_mem_write_data_out),
        .rst(rst_1),
        .stall_request(ex_0_stall_request),
        .ex_load_flag(ex_0_ex_load_flag),
        .cp0_write_en(ex_0_cp0_write_en),
        .cp0_addr_out(ex_0_cp0_addr_out),
        .cp0_write_data_out(ex_0_cp0_write_data_out),
        .cp0_write_flag_in(idex_0_cp0_write_flag_out),
        .cp0_read_flag_in(idex_0_cp0_read_flag_out),
        .cp0_addr_in(idex_0_cp0_addr_out),
        .cp0_write_data_in(idex_0_cp0_write_data_out),
        .cp0_read_data_in(cp0readproxy_0_cp0_read_data_out),
        .mult_div_done_flag(multdiv_0_done),
        .mult_div_result(multdiv_0_result),
        .exception_type_in(idex_0_exception_type_out),
        .delayslot_flag_in(idex_0_delayslot_flag_out),
        .current_pc_addr_in(idex_0_current_pc_addr_out),
        .exception_type_out(ex_0_exception_type_out),
        .delayslot_flag_out(ex_0_delayslot_flag_out),
        .current_pc_addr_out(ex_0_current_pc_addr_out)
    );

    EXMEM exmem_0(
        .result_in(ex_0_result_out),
        .write_reg_en_in(ex_0_write_reg_en_out),
        .write_reg_addr_in(ex_0_write_reg_addr_out),
        .result_out(exmem_0_result_out),
        .write_reg_en_out(exmem_0_write_reg_en_out),
        .write_reg_addr_out(exmem_0_write_reg_addr_out),
        .hilo_write_en_in(ex_0_hilo_write_en),
        .hi_in(ex_0_hi_out),
        .lo_in(ex_0_lo_out),
        .hilo_write_en_out(exmem_0_hilo_write_en_out),
        .hi_out(exmem_0_hi_out),
        .lo_out(exmem_0_lo_out),
        .mem_read_flag_in(ex_0_mem_read_flag_out),
        .mem_write_flag_in(ex_0_mem_write_flag_out),
        .mem_sign_ext_flag_in(ex_0_mem_sign_ext_flag_out),
        .mem_sel_in(ex_0_mem_sel_out),
        .mem_write_data_in(ex_0_mem_write_data_out),
        .mem_read_flag_out(exmem_0_mem_read_flag_out),
        .mem_write_flag_out(exmem_0_mem_write_flag_out),
        .mem_sign_ext_flag_out(exmem_0_mem_sign_ext_flag_out),
        .mem_sel_out(exmem_0_mem_sel_out),
        .mem_write_data_out(exmem_0_mem_write_data_out),
        .clk(clk_1),
        .rst(rst_1),
        .stall_current_stage(pipelinecontroller_0_stall_ex),
        .stall_next_stage(pipelinecontroller_0_stall_mem),
        .cp0_write_en_out(exmem_0_cp0_write_en_out),
        .cp0_addr_out(exmem_0_cp0_addr_out),
        .cp0_write_data_out(exmem_0_cp0_write_data_out),
        .cp0_write_en_in(ex_0_cp0_write_en),
        .cp0_addr_in(ex_0_cp0_addr_out),
        .cp0_write_data_in(ex_0_cp0_write_data_out),
        .flush(pipelinecontroller_0_flush),
        .exception_type_in(ex_0_exception_type_out),
        .delayslot_flag_in(ex_0_delayslot_flag_out),
        .current_pc_addr_in(ex_0_current_pc_addr_out),
        .exception_type_out(exmem_0_exception_type_out),
        .delayslot_flag_out(exmem_0_delayslot_flag_out),
        .current_pc_addr_out(exmem_0_current_pc_addr_out)
    );

    RegReadProxy regreadproxy_0(
        .read_addr_2(id_0_reg_addr_2),
        .read_addr_1(id_0_reg_addr_1),
        .read_en_2(id_0_reg_read_en_2),
        .read_en_1(id_0_reg_read_en_1),
        .data_from_ex(ex_0_result_out),
        .reg_write_en_from_ex(ex_0_write_reg_en_out),
        .reg_write_addr_from_ex(ex_0_write_reg_addr_out),
        .data_from_mem(mem_0_result_out),
        .reg_write_en_from_mem(mem_0_write_reg_en_out),
        .reg_write_addr_from_mem(mem_0_write_reg_addr_out),
        .read_data_1(regreadproxy_0_read_data_1),
        .read_data_2(regreadproxy_0_read_data_2),
        .data_1_from_reg(regfile_0_read_data_1),
        .data_2_from_reg(regfile_0_read_data_2),
        .load_related_1(regreadproxy_0_load_related_1),
        .load_related_2(regreadproxy_0_load_related_2),
        .ex_load_flag(ex_0_ex_load_flag),
        .mem_load_flag(mem_0_mem_load_flag)
    );

    HILO hilo_0(
        .hi(hilo_0_hi),
        .lo(hilo_0_lo),
        .clk(clk_1),
        .rst(rst_1),
        .write_en(wb_0_hilo_write_en_out),
        .hi_in(wb_0_hi_out),
        .lo_in(wb_0_lo_out)
    );

    HILOReadProxy hiloreadproxy_0(
        .hi_in(hilo_0_hi),
        .lo_in(hilo_0_lo),
        .mem_hilo_write_en(mem_0_hilo_write_en_out),
        .mem_hi_in(mem_0_hi_out),
        .mem_lo_in(mem_0_lo_out),
        .hi_out(hiloreadproxy_0_hi_out),
        .lo_out(hiloreadproxy_0_lo_out),
        .wb_hilo_write_en(wb_0_hilo_write_en_out),
        .wb_hi_in(wb_0_hi_out),
        .wb_lo_in(wb_0_lo_out)
    );

    CP0ReadProxy cp0readproxy_0(
        .wb_cp0_write_flag(wb_0_cp0_write_en),
        .wb_cp0_write_addr(wb_0_cp0_addr_out),
        .wb_cp0_data_in(wb_0_cp0_write_data_out),
        .mem_cp0_write_flag(mem_0_cp0_write_en_out),
        .mem_cp0_write_addr(mem_0_cp0_addr_out),
        .mem_cp0_data_in(mem_0_cp0_write_data_out),
        .cp0_read_addr(ex_0_cp0_addr_out),
        .cp0_read_data_in(cp0_0_data_out),
        .cp0_read_data_out(cp0readproxy_0_cp0_read_data_out),
        .cp0_status_in(cp0_0_status),
        .cp0_cause_in(cp0_0_cause),
        .cp0_epc_in(cp0_0_epc),
        .cp0_epc_out(cp0readproxy_0_cp0_epc_out),
        .cp0_cause_out(cp0readproxy_0_cp0_cause_out),
        .cp0_status_out(cp0readproxy_0_cp0_status_out)
    );

    MultDiv multdiv_0(
        .funct(idex_0_funct_out),
        .operand_1(idex_0_operand_1_out),
        .operand_2(idex_0_operand_2_out),
        .clk(clk_1),
        .rst(rst_1),
        .done(multdiv_0_done),
        .result(multdiv_0_result),
        .flush(pipelinecontroller_0_flush)
    );

    IDEX idex_0(
        .write_reg_en_in(id_0_write_reg_en),
        .write_reg_addr_in(id_0_write_reg_addr),
        .operand_2_in(id_0_operand_2),
        .operand_1_in(id_0_operand_1),
        .shamt_in(id_0_shamt),
        .funct_in(id_0_funct),
        .funct_out(idex_0_funct_out),
        .shamt_out(idex_0_shamt_out),
        .operand_1_out(idex_0_operand_1_out),
        .operand_2_out(idex_0_operand_2_out),
        .write_reg_en_out(idex_0_write_reg_en_out),
        .write_reg_addr_out(idex_0_write_reg_addr_out),
        .mem_read_flag_in(id_0_mem_read_flag),
        .mem_write_flag_in(id_0_mem_write_flag),
        .mem_sign_ext_flag_in(id_0_mem_sign_ext_flag),
        .mem_sel_in(id_0_mem_sel),
        .mem_write_data_in(id_0_mem_write_data),
        .mem_read_flag_out(idex_0_mem_read_flag_out),
        .mem_write_flag_out(idex_0_mem_write_flag_out),
        .mem_sign_ext_flag_out(idex_0_mem_sign_ext_flag_out),
        .mem_sel_out(idex_0_mem_sel_out),
        .mem_write_data_out(idex_0_mem_write_data_out),
        .clk(clk_1),
        .rst(rst_1),
        .stall_current_stage(pipelinecontroller_0_stall_id),
        .stall_next_stage(pipelinecontroller_0_stall_ex),
        .cp0_write_flag_in(id_0_cp0_write_flag),
        .cp0_read_flag_in(id_0_cp0_read_flag),
        .cp0_addr_in(id_0_cp0_addr),
        .cp0_write_data_in(id_0_cp0_write_data),
        .cp0_write_flag_out(idex_0_cp0_write_flag_out),
        .cp0_read_flag_out(idex_0_cp0_read_flag_out),
        .cp0_addr_out(idex_0_cp0_addr_out),
        .cp0_write_data_out(idex_0_cp0_write_data_out),
        .flush(pipelinecontroller_0_flush),
        .delayslot_flag_in(id_0_delayslot_flag_out),
        .exception_type_in(id_0_exception_type),
        .current_pc_addr_in(id_0_current_pc_addr),
        .current_delayslot_flag(idex_0_current_delayslot_flag),
        .exception_type_out(idex_0_exception_type_out),
        .delayslot_flag_out(idex_0_delayslot_flag_out),
        .current_pc_addr_out(idex_0_current_pc_addr_out),
        .next_delayslot_flag(id_0_next_delayslot_flag_out)
    );

    MEM mem_0(
        .result_in(exmem_0_result_out),
        .write_reg_en_in(exmem_0_write_reg_en_out),
        .write_reg_addr_in(exmem_0_write_reg_addr_out),
        .result_out(mem_0_result_out),
        .write_reg_en_out(mem_0_write_reg_en_out),
        .write_reg_addr_out(mem_0_write_reg_addr_out),
        .hilo_write_en_in(exmem_0_hilo_write_en_out),
        .hi_in(exmem_0_hi_out),
        .lo_in(exmem_0_lo_out),
        .hilo_write_en_out(mem_0_hilo_write_en_out),
        .hi_out(mem_0_hi_out),
        .lo_out(mem_0_lo_out),
        .mem_read_flag_in(exmem_0_mem_read_flag_out),
        .mem_write_flag_in(exmem_0_mem_write_flag_out),
        .mem_sign_ext_flag_in(exmem_0_mem_sign_ext_flag_out),
        .mem_sel_in(exmem_0_mem_sel_out),
        .mem_write_data(exmem_0_mem_write_data_out),
        .ram_write_data(mem_0_ram_write_data),
        .ram_write_en(mem_0_ram_write_sel),
        .ram_en(mem_0_ram_en),
        .rst(rst_1),
        .mem_write_flag_out(mem_0_mem_write_flag_out),
        .mem_sign_ext_flag_out(mem_0_mem_sign_ext_flag_out),
        .mem_sel_out(mem_0_mem_sel_out),
        .mem_read_flag_out(mem_0_mem_read_flag_out),
        .mem_load_flag(mem_0_mem_load_flag),
        .cp0_write_en_out(mem_0_cp0_write_en_out),
        .cp0_addr_out(mem_0_cp0_addr_out),
        .cp0_write_data_out(mem_0_cp0_write_data_out),
        .cp0_write_en_in(exmem_0_cp0_write_en_out),
        .cp0_addr_in(exmem_0_cp0_addr_out),
        .cp0_write_data_in(exmem_0_cp0_write_data_out),
        .exception_type_in(exmem_0_exception_type_out),
        .delayslot_flag_in(exmem_0_delayslot_flag_out),
        .current_pc_addr_in(exmem_0_current_pc_addr_out),
        .current_pc_addr_out(mem_0_current_pc_addr_out),
        .cp0_epc_in(cp0readproxy_0_cp0_epc_out),
        .cp0_cause_in(cp0readproxy_0_cp0_cause_out),
        .cp0_status_in(cp0readproxy_0_cp0_status_out),
        .cp0_badvaddr_write_data(mem_0_cp0_badvaddr_write_data),
        .delayslot_flag_out(mem_0_delayslot_flag_out),
        .exception_type_out(mem_0_exception_type_out),
        .cp0_epc_out(mem_0_cp0_epc_out),
        .ram_addr(mem_0_ram_addr)
    );

    PC pc_0(
        .clk(clk_1),
        .rst(rst_1),
        .rom_en(pc_0_rom_en),
        .rom_write_en(pc_0_rom_write_en),
        .rom_write_data(pc_0_rom_write_data),
        .stall_pc(pipelinecontroller_0_stall_pc),
        .rom_addr(pc_0_rom_addr),
        .pc(pc_0_pc),
        .flush(pipelinecontroller_0_flush),
        .exc_pc(pipelinecontroller_0_exc_pc),
        .branch_addr(id_0_branch_addr),
        .branch_flag(id_0_branch_flag)
    );

    CP0 cp0_0(
        .clk(clk_1),
        .rst(rst_1),
        .write_en(wb_0_cp0_write_en),
        .write_addr(wb_0_cp0_addr_out),
        .write_data(wb_0_cp0_write_data_out),
        .interrupt(interrupt_1),
        .read_addr(ex_0_cp0_addr_out),
        .data_out(cp0_0_data_out),
        .current_pc_addr(mem_0_current_pc_addr_out),
        .status(cp0_0_status),
        .cause(cp0_0_cause),
        .epc(cp0_0_epc),
        .cp0_badvaddr_write_data(mem_0_cp0_badvaddr_write_data),
        .delayslot_flag(mem_0_delayslot_flag_out),
        .exception_type(mem_0_exception_type_out)
    );

    ID id_0(
        .addr(ifid_0_addr_out),
        .write_reg_en(id_0_write_reg_en),
        .write_reg_addr(id_0_write_reg_addr),
        .operand_2(id_0_operand_2),
        .operand_1(id_0_operand_1),
        .shamt(id_0_shamt),
        .funct(id_0_funct),
        .reg_addr_2(id_0_reg_addr_2),
        .reg_addr_1(id_0_reg_addr_1),
        .reg_read_en_2(id_0_reg_read_en_2),
        .reg_read_en_1(id_0_reg_read_en_1),
        .reg_data_1(regreadproxy_0_read_data_1),
        .reg_data_2(regreadproxy_0_read_data_2),
        .mem_read_flag(id_0_mem_read_flag),
        .mem_write_flag(id_0_mem_write_flag),
        .mem_sign_ext_flag(id_0_mem_sign_ext_flag),
        .mem_sel(id_0_mem_sel),
        .mem_write_data(id_0_mem_write_data),
        .rst(rst_1),
        .stall_request(id_0_stall_request),
        .load_related_1(regreadproxy_0_load_related_1),
        .load_related_2(regreadproxy_0_load_related_2),
        .inst(ifid_0_inst_out),
        .cp0_write_flag(id_0_cp0_write_flag),
        .cp0_read_flag(id_0_cp0_read_flag),
        .cp0_addr(id_0_cp0_addr),
        .cp0_write_data(id_0_cp0_write_data),
        .delayslot_flag_out(id_0_delayslot_flag_out),
        .exception_type(id_0_exception_type),
        .current_pc_addr(id_0_current_pc_addr),
        .delayslot_flag_in(idex_0_current_delayslot_flag),
        .branch_addr(id_0_branch_addr),
        .branch_flag(id_0_branch_flag),
        .next_delayslot_flag_out(id_0_next_delayslot_flag_out)
    );

    MEMWB memwb_0(
        .result_in(mem_0_result_out),
        .write_reg_en_in(mem_0_write_reg_en_out),
        .write_reg_addr_in(mem_0_write_reg_addr_out),
        .hilo_write_en_in(mem_0_hilo_write_en_out),
        .hi_in(mem_0_hi_out),
        .lo_in(mem_0_lo_out),
        .ram_read_data_in(ram_read_data_1),
        .clk(clk_1),
        .rst(rst_1),
        .stall_current_stage(pipelinecontroller_0_stall_mem),
        .stall_next_stage(pipelinecontroller_0_stall_wb),
        .mem_write_flag_in(mem_0_mem_write_flag_out),
        .mem_sign_ext_flag_in(mem_0_mem_sign_ext_flag_out),
        .mem_sel_in(mem_0_mem_sel_out),
        .mem_read_flag_out(memwb_0_mem_read_flag_out),
        .ram_read_data_out(memwb_0_ram_read_data_out),
        .mem_write_flag_out(memwb_0_mem_write_flag_out),
        .mem_sign_ext_flag_out(memwb_0_mem_sign_ext_flag_out),
        .mem_sel_out(memwb_0_mem_sel_out),
        .result_out(memwb_0_result_out),
        .write_reg_en_out(memwb_0_write_reg_en_out),
        .write_reg_addr_out(memwb_0_write_reg_addr_out),
        .hilo_write_en_out(memwb_0_hilo_write_en_out),
        .hi_out(memwb_0_hi_out),
        .lo_out(memwb_0_lo_out),
        .current_pc_addr_out(memwb_0_debug_pc_addr_out),
        .mem_read_flag_in(mem_0_mem_read_flag_out),
        .cp0_write_en_out(memwb_0_cp0_write_en_out),
        .cp0_addr_out(memwb_0_cp0_addr_out),
        .cp0_write_data_out(memwb_0_cp0_write_data_out),
        .cp0_write_en_in(mem_0_cp0_write_en_out),
        .cp0_addr_in(mem_0_cp0_addr_out),
        .cp0_write_data_in(mem_0_cp0_write_data_out),
        .flush(pipelinecontroller_0_flush),
        .current_pc_addr_in(mem_0_current_pc_addr_out)
    );

    PipelineController pipelinecontroller_0(
        .rst(rst_1),
        .request_from_id(id_0_stall_request),
        .request_from_ex(ex_0_stall_request),
        .stall_pc(pipelinecontroller_0_stall_pc),
        .stall_if(pipelinecontroller_0_stall_if),
        .stall_id(pipelinecontroller_0_stall_id),
        .stall_ex(pipelinecontroller_0_stall_ex),
        .stall_mem(pipelinecontroller_0_stall_mem),
        .stall_wb(pipelinecontroller_0_stall_wb),
        .flush(pipelinecontroller_0_flush),
        .exc_pc(pipelinecontroller_0_exc_pc),
        .exception_type(mem_0_exception_type_out),
        .cp0_epc(mem_0_cp0_epc_out),
        .stall_all(stall_all_1)
    );

    WB wb_0(
        .rst(rst_1),
        .debug_reg_write_en(memwb_0_debug_reg_write_en),
        .mem_read_flag(memwb_0_mem_read_flag_out),
        .ram_read_data(memwb_0_ram_read_data_out),
        .mem_write_flag(memwb_0_mem_write_flag_out),
        .mem_sign_ext_flag(memwb_0_mem_sign_ext_flag_out),
        .mem_sel(memwb_0_mem_sel_out),
        .result_in(memwb_0_result_out),
        .result_out(wb_0_result_out),
        .write_reg_en_in(memwb_0_write_reg_en_out),
        .write_reg_en_out(wb_0_write_reg_en_out),
        .write_reg_addr_in(memwb_0_write_reg_addr_out),
        .write_reg_addr_out(wb_0_write_reg_addr_out),
        .hilo_write_en_in(memwb_0_hilo_write_en_out),
        .hilo_write_en_out(wb_0_hilo_write_en_out),
        .hi_in(memwb_0_hi_out),
        .hi_out(wb_0_hi_out),
        .lo_in(memwb_0_lo_out),
        .lo_out(wb_0_lo_out),
        .debug_pc_addr_in(memwb_0_debug_pc_addr_out),
        .debug_pc_addr_out(wb_0_debug_pc_addr_out),
        .cp0_write_en_out(wb_0_cp0_write_en),
        .cp0_addr_out(wb_0_cp0_addr_out),
        .cp0_write_data_out(wb_0_cp0_write_data_out),
        .cp0_write_en_in(memwb_0_cp0_write_en_out),
        .cp0_addr_in(memwb_0_cp0_addr_out),
        .cp0_write_data_in(memwb_0_cp0_write_data_out)
    );

endmodule // Uranus
